name: Maven Clean Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Maven Clean Build
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:17-mvn3

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.7

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress
